/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AuthService,
} from './services/auth';
import {
  DatabaseService,
} from './services/database';

export namespace Components {
  interface AppRoot {}
  interface MlApps {}
  interface MlContact {}
  interface MlHome {
    'auth': AuthService;
    'db': DatabaseService;
    'session': any;
  }
  interface MlVideos {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMlAppsElement extends Components.MlApps, HTMLStencilElement {}
  var HTMLMlAppsElement: {
    prototype: HTMLMlAppsElement;
    new (): HTMLMlAppsElement;
  };

  interface HTMLMlContactElement extends Components.MlContact, HTMLStencilElement {}
  var HTMLMlContactElement: {
    prototype: HTMLMlContactElement;
    new (): HTMLMlContactElement;
  };

  interface HTMLMlHomeElement extends Components.MlHome, HTMLStencilElement {}
  var HTMLMlHomeElement: {
    prototype: HTMLMlHomeElement;
    new (): HTMLMlHomeElement;
  };

  interface HTMLMlVideosElement extends Components.MlVideos, HTMLStencilElement {}
  var HTMLMlVideosElement: {
    prototype: HTMLMlVideosElement;
    new (): HTMLMlVideosElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'ml-apps': HTMLMlAppsElement;
    'ml-contact': HTMLMlContactElement;
    'ml-home': HTMLMlHomeElement;
    'ml-videos': HTMLMlVideosElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface MlApps extends JSXBase.HTMLAttributes<HTMLMlAppsElement> {}
  interface MlContact extends JSXBase.HTMLAttributes<HTMLMlContactElement> {}
  interface MlHome extends JSXBase.HTMLAttributes<HTMLMlHomeElement> {
    'auth'?: AuthService;
    'db'?: DatabaseService;
    'session'?: any;
  }
  interface MlVideos extends JSXBase.HTMLAttributes<HTMLMlVideosElement> {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'ml-apps': MlApps;
    'ml-contact': MlContact;
    'ml-home': MlHome;
    'ml-videos': MlVideos;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


