/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AuthService,
} from './services/auth';
import {
  DatabaseService,
} from './services/database';

export namespace Components {
  interface AppRoot {}
  interface MlHome {
    'auth': AuthService;
    'db': DatabaseService;
    'session': any;
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMlHomeElement extends Components.MlHome, HTMLStencilElement {}
  var HTMLMlHomeElement: {
    prototype: HTMLMlHomeElement;
    new (): HTMLMlHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'ml-home': HTMLMlHomeElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface MlHome extends JSXBase.HTMLAttributes<HTMLMlHomeElement> {
    'auth'?: AuthService;
    'db'?: DatabaseService;
    'session'?: any;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'ml-home': MlHome;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


